# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-04-20 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='show_number',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='quote',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
