# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-04-21 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
