# Generated by Django 2.2.5 on 2019-10-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0002_auto_20191010_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
