# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-04-21 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0003_auto_20200421_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
