# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-30 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0004_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='roster/')),
                ('player_number', models.CharField(max_length=100)),
                ('player_name', models.CharField(max_length=100)),
                ('player_info', models.TextField(max_length=300)),
                ('player_quote', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
