# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-04-04 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0005_roster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roster',
            old_name='player_info',
            new_name='player_bio',
        ),
    ]
