# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-09 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0005_notice_sitelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='color',
            field=models.CharField(choices=[('green', 'green'), ('red', 'red'), ('blue', 'blue')], max_length=256, null=True),
        ),
    ]
