# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-10 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0006_notice_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelink',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitelink',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitelink',
            name='twiiter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
