# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-10 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0007_auto_20200510_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitelink',
            old_name='twiiter',
            new_name='twitter',
        ),
        migrations.RemoveField(
            model_name='sitelink',
            name='phone',
        ),
        migrations.AddField(
            model_name='sitelink',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
