# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-04-06 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0007_auto_20200404_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='bio',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='roster',
            name='image',
            field=models.ImageField(upload_to='roster'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='roster',
            name='number',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='roster',
            name='quote',
            field=models.TextField(max_length=1000),
        ),
    ]
