# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-04-06 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0008_auto_20200406_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hd_event_logo',
            field=models.ImageField(blank=True, upload_to='events'),
        ),
    ]
