# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-11 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0009_auto_20200510_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitelink',
            old_name='phone_number',
            new_name='email_CONTACT',
        ),
        migrations.AddField(
            model_name='sitelink',
            name='phone_number_CONTACT',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='sitelink',
            name='phone_number_HOME',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
