# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-04-06 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0011_auto_20200406_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
