# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-12 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0012_auto_20200511_0046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterUser',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
