# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-16 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteruser',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
